# Topic modelling 

This workbook implements topic modelling - using the optimal approach from 1_0_2_topic_modelling_practise.ipynb.

In [ ]:
import pandas as pd
import numpy as np
import string 
from datasets import Dataset

import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import CountVectorizer
from scipy.cluster import hierarchy as sch

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired
from sentence_transformers import SentenceTransformer

import openai
from bertopic.representation import OpenAI

from gensim import corpora
from gensim.models import LdaModel

from hdbscan import HDBSCAN
from umap import UMAP

from database.topics import Topics

import sys
sys.path.append('../pipeline')
from nlp_tasks import NLP_Tasks
from comments_saver import CommentsSaver

/opt/conda/envs/nlp_env_analysis/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Read the remote database of comments

In [2]:
cs = CommentsSaver(env='dev')
df = cs.read_all()
print('df shape:', df.shape)

Connecting to the ai4ci-db-dev database...
Successfully connected to ai4ci-db-dev.
df shape: (30393, 12)

In [3]:
df.columns

Index(['id', 'council', 'comment_id', 'application_id', 'address', 'stance',
       'date', 'comment_text', 'add_date', 'lat', 'lon',
       'cleaned_comment_text'],
      dtype='object')

In [ ]:
model = SentenceTransformer("Bea-Taylor/objection_fine_tuned_4")
tokenizer = model.tokenizer

### Pre-process the data

1. Remove non-ASCII characters 

Just because otherwise these are a bit of a pain

2. Remove place names 

I don't want the topics identified to relate to the place names of specific applications (i.e. Durning Hall or Forest Gate) - as I want the topics to be generalised themes, common across applications - hence I remove all place names. This uses Named Entity Recognition (NER), I intially tried using the out of the box bog-standard model, but it wasn't able to recognise more specific British place names. Instead I use the "cjber/reddit-ner-place_names" - which has specifically been trained to recognise these sorts of place names. 

```
place_ner_pipeline = pipeline(
    task="ner",
    model="cjber/reddit-ner-place_names",
    tokenizer="cjber/reddit-ner-place_names",
    aggregation_strategy="first",
)
```

3. Remove peoples names 

I don't want the topics identified to relate to individuals. Also, this helps anonymise the data. 

```
people_ner_pipeline = pipeline(
            task="ner",
            model="dslim/bert-base-NER",
            tokenizer="dslim/bert-base-NER",
            aggregation_strategy="first"
        )
```

NOTE: I leave in stop words and the like --- I'm using a sentence transformer ("Bea-Taylor/objection_fine_tuned" which was fine tuned from "all-MiniLM-L6-v2") so I want to preserve sentence structure.

In [ ]:
nlp_tasks = NLP_Tasks()
# split text on newlines, this function preserves the metadata by exploding the dataframe
train_df_split = nlp_tasks.split_text_on_newline(df=df[:1000], column='cleaned_comment_text')
print(len(train_df_split))

Device set to use cpu
Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

In [8]:
cleaned_text = train_df_split['cleaned_comment_text'].tolist()

### BertTopic modelling

I have done some pre-processing of the free text data (see above). Below I specify some of the models hyper parameters.

In [ ]:
# this controls the embedding model
sentence_model = SentenceTransformer("Bea-Taylor/objection_fine_tuned_4")
embeddings = sentence_model.encode(cleaned_text, show_progress_bar=True)

# this controls the seed - allowing for reproducible maps 
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=43)

# this controls the topic parameters
hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

# this controls the topic representation
# GPT-3.5
client = openai.OpenAI(api_key="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")
prompt = """
I have a topic that contains the following documents:
[DOCUMENTS]
The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short but highly descriptive topic label of at most 5 words. Make sure it is in the following format:
topic: <topic label>
"""
openai_model = OpenAI(client, model="gpt-4o-mini", exponential_backoff=True, prompt=prompt)

representation_model = {
    "OpenAI": openai_model,
}

In [ ]:
# define the topic model with parameters 
topic_model = BERTopic(embedding_model=embeddings,
                       hdbscan_model=hdbscan_model, 
                       umap_model=umap_model, 
                       representation_model=representation_model,
                       verbose=True, 
                       calculate_probabilities=True)

In [ ]:
# fit the model to the cleaned text
topics, probs = topic_model.fit_transform(cleaned_text, embeddings)

2025-06-10 15:36:51,430 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-10 15:37:02,551 - BERTopic - Dimensionality - Completed ✓
2025-06-10 15:37:02,554 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-10 15:37:10,821 - BERTopic - Cluster - Completed ✓
2025-06-10 15:37:10,829 - BERTopic - Representation - Extracting topics from clusters using representation models.
  0%|          | 0/203 [1:06:26<?, ?it/s]

KeyboardInterrupt:

In [ ]:
# Display the topics found
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1500,-1_to_for_the_this,"[to, for, the, this, and, of, in, be, planning...",[I strongly oppose to this building applicatio...
1,0,89,0_family_bedroom_flats_roofs,"[family, bedroom, flats, roofs, home, flat, un...",[Issue with Roof & Green TerracesGreen roofs a...
2,1,80,1_trees_report_groups_lime,"[trees, report, groups, lime, group, mature, p...",[? G7 group of trees all lie within the proper...
3,2,77,2_comments_hearing_comment_judicial,"[comments, hearing, comment, judicial, renewal...","[We have the following comments:, We have deep..."
4,3,71,3_objections_my_petition_follows,"[objections, my, petition, follows, read, plan...","[My main objections are as follows, The object..."
...,...,...,...,...,...
198,197,11,197_driveway_inaccurate_noise_buffer,"[driveway, inaccurate, noise, buffer, traffic,...",[1. Inaccurate and misleading submission docum...
199,198,11,198_sincerely_yours__,"[sincerely, yours, , , , , , , , ]","[Yours sincerely,, Yours sincerely,, Yours sin..."
200,199,11,199_bin_stores_curtilage_212719ful,"[bin, stores, curtilage, 212719ful, extend, cy...",[Subsection 1(n) states that development is no...
201,200,10,200_unforeseen_anxiety_upset_covid19,"[unforeseen, anxiety, upset, covid19, delivere...",[These planning applications are causing stres...
202,201,10,201_public_informed_arrived_unmade,"[public, informed, arrived, unmade, insensitiv...","[Despite numerous requests, the Council on its..."

In [ ]:
# function which string the represnetation words toegther into a single string
def get_topic_words(topic_model, topic_id):
    topic_words = topic_model.get_topic(topic_id)
    return ", ".join([word for word, _ in topic_words])

In [ ]:
# identify the topics with a probability greater than 0.02
# index where probs[0]>0.02
high_prob_indices = np.where(probs[0] > 0.02)[0]
# Get the topics for these indices
high_prob_topics = [get_topic_words(topic_model, i) for i in high_prob_indices]
# Get the probabilities for these indices
high_prob_probs = [probs[0][i] for i in high_prob_indices]
for topic, prob in zip(high_prob_topics, high_prob_probs):
    print(f"Topic: [{topic}], Probability: {prob:.4f}")

Topic: [park, underground, car, specified, quantum, 2017, 108, access, subsequent, completed], Probability: 0.1482

In [ ]:
# add the topics and probabilities to the train_df_split dataframe

all_topic_list =[]
all_prob_list = []
for i in range(len(train_df_split)):
    high_prob_indices = np.where(probs[i] > 0.02)[0]
    high_prob_topics = [get_topic_words(topic_model, i) for i in high_prob_indices]
    high_prob_probs = [probs[i][j] for j in high_prob_indices]
    topic_list = []
    prob_list = []
    for topic, prob in zip(high_prob_topics, high_prob_probs):
        topic_list.append(topic)
        prob_list.append(prob)
    all_topic_list.append(topic_list)
    all_prob_list.append(prob_list)

train_df_split['topics'] = all_topic_list
train_df_split['probs'] = all_prob_list

In [ ]:
train_df_split

,id,council,comment_id,application_id,address,stance,date,comment_text,add_date,lat,lon,cleaned_comment_text,original_comment_id,topics,probs
0,108039,Ealing,214950FUL_129,214950FUL,57A Woodhurst Road Acton London W3 6SR W3 6SR,Objects,2021-09-15,I am not sure why Ealing Council are hell bent...,2025-05-01,51.510510,-0.268640,I am not sure why Council are hell bent of bui...,0,"[park, underground, car, specified, quantum, 2...",[0.1482378501837773]
1,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,It is obvious from all the detailed reading of...,1,"[comments, hearing, comment, judicial, renewal...",[0.03403126291932642]
2,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,The proposed development would be entirely out...,1,"[park, residual, playground, school, 14, our, ...",[1.0]
3,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,The area on which the property is proposed to ...,1,"[biodiversity, bap, duty, bats, wildlife, habi...",[0.6223742666706982]
4,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,It is also inappropriate that residents contin...,1,"[heritage, asset, lodges, nile, preserved, sta...",[0.020380490857612326]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6845,81834,Ealing,205161FUL_107,205161FUL,19 Lillian Avenue London W3 9AN,Objects,2021-02-06,The proposal is far from fit for purpose. Curr...,2025-04-09,51.502026,-0.284986,"- If parked on the road, where a high rate of ...",998,"[bins, refuse, waste, bin, rubbish, recycling,...",[0.6857589171189096]
6846,81834,Ealing,205161FUL_107,205161FUL,19 Lillian Avenue London W3 9AN,Objects,2021-02-06,The proposal is far from fit for purpose. Curr...,2025-04-09,51.502026,-0.284986,https://www..gov.uk/downloads/201167/rubbish_a...,998,"[bins, refuse, waste, bin, rubbish, recycling,...",[1.0]
6847,81834,Ealing,205161FUL_107,205161FUL,19 Lillian Avenue London W3 9AN,Objects,2021-02-06,The proposal is far from fit for purpose. Curr...,2025-04-09,51.502026,-0.284986,"Finally, from a personal standpoint, I would l...",998,"[parking, spaces, already, there, allocated, 1...","[0.025656633649377543, 0.1656856770903388, 0.0..."
6848,76454,Barnet,24/1146/OUT_13,24/1146/OUT,91 Margaret Road New Barnet EN4 9RA,Objects,2024-04-20,The details of this audacious planning applica...,2025-04-08,51.650399,-0.164110,The details of this audacious planning applica...,999,"[unforeseen, anxiety, upset, covid19, delivere...",[0.07481701160027006]
6849,76454,Barnet,24/1146/OUT_13,24/1146/OUT,91 Margaret Road New Barnet EN4 9RA,Objects,2024-04-20,The details of this audacious planning applica...,2025-04-08,51.650399,-0.164110,The applicant is not interested in getting the...,999,"[objections, my, petition, follows, read, plan...",[0.5813214727119856]

In [ ]:
# merge the sentences back to the original comments
new_df = nlp_tasks.merge_sentences_back_to_comments(train_df_split, text_column='cleaned_comment_text',
                                           topic_column='topics')

In [ ]:
new_df['topics'][1]

['amendment, maisonettes, reinstated, amended, submission, forward, elsewhere, proposals, mews, brought',
 'biodiversity, bap, duty, bats, wildlife, habitat, species, tit, 2027, ealings',
 'comments, hearing, comment, judicial, renewal, review, appeal, reading, have, find',
 'heritage, asset, lodges, nile, preserved, status, archaeological, grounds, possible, assessment',
 'park, residual, playground, school, 14, our, llanvanor, bin, space, urban',
 'refused, application, refuse, 223124, should, opportunity, barrister, objection, writing, dismiss']