# Topic modelling 

This workbook implements topic modelling - using the optimal approach from 1_0_2_topic_modelling_practise.ipynb.

In [15]:
import pandas as pd
import numpy as np
import string 
from datasets import Dataset

import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import CountVectorizer
from scipy.cluster import hierarchy as sch

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired
from sentence_transformers import SentenceTransformer

import openai
from bertopic.representation import OpenAI, MaximalMarginalRelevance, PartOfSpeech, KeyBERTInspired

from transformers import T5Tokenizer, T5ForConditionalGeneration

from gensim import corpora
from gensim.models import LdaModel

from hdbscan import HDBSCAN
from umap import UMAP

from database.topics import Topics

import sys
sys.path.append('../pipeline')
from nlp_tasks import NLP_Tasks
from comments_saver import CommentsSaver

### Read the remote database of comments

In [16]:
cs = CommentsSaver(env='dev')
df = cs.read_all()
print('df shape:', df.shape)

Connecting to the ai4ci-db-dev database...
Successfully connected to ai4ci-db-dev.
df shape: (30393, 12)

In [17]:
df.columns

Index(['id', 'council', 'comment_id', 'application_id', 'address', 'stance',
       'date', 'comment_text', 'add_date', 'lat', 'lon',
       'cleaned_comment_text'],
      dtype='object')

In [18]:
model = SentenceTransformer("Bea-Taylor/objection_fine_tuned_4")
tokenizer = model.tokenizer

### Pre-process the data

1. Remove non-ASCII characters 

Just because otherwise these are a bit of a pain

2. Remove place names 

I don't want the topics identified to relate to the place names of specific applications (i.e. Durning Hall or Forest Gate) - as I want the topics to be generalised themes, common across applications - hence I remove all place names. This uses Named Entity Recognition (NER), I intially tried using the out of the box bog-standard model, but it wasn't able to recognise more specific British place names. Instead I use the "cjber/reddit-ner-place_names" - which has specifically been trained to recognise these sorts of place names. 

```
place_ner_pipeline = pipeline(
    task="ner",
    model="cjber/reddit-ner-place_names",
    tokenizer="cjber/reddit-ner-place_names",
    aggregation_strategy="first",
)
```

3. Remove peoples names 

I don't want the topics identified to relate to individuals. Also, this helps anonymise the data. 

```
people_ner_pipeline = pipeline(
            task="ner",
            model="dslim/bert-base-NER",
            tokenizer="dslim/bert-base-NER",
            aggregation_strategy="first"
        )
```

NOTE: I leave in stop words and the like --- I'm using a sentence transformer ("Bea-Taylor/objection_fine_tuned" which was fine tuned from "all-MiniLM-L6-v2") so I want to preserve sentence structure.

In [19]:
nlp_tasks = NLP_Tasks()
# split text on newlines, this function preserves the metadata by exploding the dataframe
train_df_split = nlp_tasks.split_text_on_newline(df=df[:1000], column='cleaned_comment_text')
print(len(train_df_split))

Device set to use cpu
Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

6850

In [20]:
cleaned_text = train_df_split['cleaned_comment_text'].tolist()

### BertTopic modelling

I have done some pre-processing of the free text data (see above). Below I specify some of the models hyper parameters.

In [21]:
# this controls the embedding model
sentence_model = SentenceTransformer("Bea-Taylor/objection_fine_tuned_4")
embeddings = sentence_model.encode(cleaned_text, show_progress_bar=True)

# this controls the seed - allowing for reproducible maps 
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=43)

# this controls the topic parameters
hdbscan_model = HDBSCAN(min_cluster_size=10, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

# NOTE: The OpenAI model is commented out because it requires a paid subscription --- which I don't have ::cry::, and without said subscription the API key doesn't work.
# # this controls the topic representation
# # GPT-3.5
# client = openai.OpenAI(api_key="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")
# prompt = """
# I have a topic that contains the following documents:
# [DOCUMENTS]
# The topic is described by the following keywords: [KEYWORDS]

# Based on the information above, extract a short but highly descriptive topic label of at most 5 words. Make sure it is in the following format:
# topic: <topic label>
# """
# openai_model = OpenAI(client, model="gpt-4o-mini", exponential_backoff=True, prompt=prompt)

# representation_model = {
#     "OpenAI": openai_model,
# }

rm_MMR = MaximalMarginalRelevance(diversity=0.3)
rm_KBERT = KeyBERTInspired()

representation_model = {
    "MaximalMarginalRelevance": rm_MMR,
    "KeyBERTInspired": rm_KBERT,
}

Batches: 100%|██████████| 215/215 [00:34<00:00,  6.21it/s]

In [22]:
# define the topic model with parameters 
topic_model = BERTopic(embedding_model=sentence_model,
                       hdbscan_model=hdbscan_model, 
                       umap_model=umap_model, 
                       representation_model=representation_model,
                       verbose=True, 
                       calculate_probabilities=True)

In [23]:
# fit the model to the cleaned text
topics, probs = topic_model.fit_transform(cleaned_text, embeddings)

2025-06-11 11:48:14,627 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-11 11:48:25,580 - BERTopic - Dimensionality - Completed ✓
2025-06-11 11:48:25,581 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-11 11:48:33,767 - BERTopic - Cluster - Completed ✓
2025-06-11 11:48:33,774 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-06-11 11:49:02,759 - BERTopic - Representation - Completed ✓

In [24]:
# Display the topics found
topic_model.get_topic_info()

,Topic,Count,Name,Representation,MaximalMarginalRelevance,KeyBERTInspired,Representative_Docs
0,-1,1500,-1_to_for_the_this,"[to, for, the, this, and, of, in, be, planning...","[to, for, the, this, and, of, in, be, planning...","[design, trees, parking, space, tree, green, l...",[I strongly oppose to this building applicatio...
1,0,89,0_family_bedroom_flats_roofs,"[family, bedroom, flats, roofs, home, flat, un...","[family, bedroom, flats, roofs, home, flat, un...","[bedroom, family, mix, bed, bedspace, breeding...","[Family houses are needed., Green roofs are pr..."
2,1,80,1_trees_report_groups_lime,"[trees, report, groups, lime, mature, group, p...","[trees, report, groups, lime, mature, group, p...","[trees, tree, apple, species, gardens, habitat...",[? G7 group of trees all lie within the proper...
3,2,77,2_comments_hearing_comment_judicial,"[comments, hearing, comment, judicial, review,...","[comments, hearing, comment, judicial, review,...","[comments, comment, objection, appeal, refusal...","[We have the following comments:, We have deep..."
4,3,71,3_objections_my_petition_read,"[objections, my, petition, read, follows, plan...","[objections, my, petition, read, follows, plan...","[objections, petition, objected, rejected, sub...","[My main objections are as follows, The object..."
...,...,...,...,...,...,...,...
198,197,11,197_driveway_buffer_noise_inaccurate,"[driveway, buffer, noise, inaccurate, traffic,...","[driveway, buffer, noise, inaccurate, traffic,...","[trees, greenery, traffic, congestion, light, ...",[1. Inaccurate and misleading submission docum...
199,198,11,198_sincerely_yours__,"[sincerely, yours, , , , , , , , ]","[sincerely, yours, , , , , , , , ]","[yours, sincerely, , , , , , , , ]","[Yours sincerely,, Yours sincerely,, Yours sin..."
200,199,11,199_bin_stores_curtilage_212719ful,"[bin, stores, curtilage, 212719ful, extend, cy...","[bin, stores, curtilage, 212719ful, extend, cy...","[amenity, waste, bin, recycling, refuse, bins,...",[Subsection 1(n) states that development is no...
201,200,10,200_unforeseen_anxiety_upset_delivered,"[unforeseen, anxiety, upset, delivered, causin...","[unforeseen, anxiety, upset, delivered, causin...","[reassurances, stress, during, distress, anxie...",[These planning applications are causing stres...
202,201,10,201_public_informed_strike_unmade,"[public, informed, strike, unmade, insensitive...","[public, informed, strike, unmade, insensitive...","[evidence, public, responses, concerns, antici...","[Despite numerous requests, the Council on its..."

In [30]:
topic_df = topic_model.get_topic_info()

In [31]:
topic_df

,Topic,Count,Name,Representation,MaximalMarginalRelevance,KeyBERTInspired,Representative_Docs
0,-1,1500,-1_to_for_the_this,"[to, for, the, this, and, of, in, be, planning...","[to, for, the, this, and, of, in, be, planning...","[design, trees, parking, space, tree, green, l...",[I strongly oppose to this building applicatio...
1,0,89,0_family_bedroom_flats_roofs,"[family, bedroom, flats, roofs, home, flat, un...","[family, bedroom, flats, roofs, home, flat, un...","[bedroom, family, mix, bed, bedspace, breeding...","[Family houses are needed., Green roofs are pr..."
2,1,80,1_trees_report_groups_lime,"[trees, report, groups, lime, mature, group, p...","[trees, report, groups, lime, mature, group, p...","[trees, tree, apple, species, gardens, habitat...",[? G7 group of trees all lie within the proper...
3,2,77,2_comments_hearing_comment_judicial,"[comments, hearing, comment, judicial, review,...","[comments, hearing, comment, judicial, review,...","[comments, comment, objection, appeal, refusal...","[We have the following comments:, We have deep..."
4,3,71,3_objections_my_petition_read,"[objections, my, petition, read, follows, plan...","[objections, my, petition, read, follows, plan...","[objections, petition, objected, rejected, sub...","[My main objections are as follows, The object..."
...,...,...,...,...,...,...,...
198,197,11,197_driveway_buffer_noise_inaccurate,"[driveway, buffer, noise, inaccurate, traffic,...","[driveway, buffer, noise, inaccurate, traffic,...","[trees, greenery, traffic, congestion, light, ...",[1. Inaccurate and misleading submission docum...
199,198,11,198_sincerely_yours__,"[sincerely, yours, , , , , , , , ]","[sincerely, yours, , , , , , , , ]","[yours, sincerely, , , , , , , , ]","[Yours sincerely,, Yours sincerely,, Yours sin..."
200,199,11,199_bin_stores_curtilage_212719ful,"[bin, stores, curtilage, 212719ful, extend, cy...","[bin, stores, curtilage, 212719ful, extend, cy...","[amenity, waste, bin, recycling, refuse, bins,...",[Subsection 1(n) states that development is no...
201,200,10,200_unforeseen_anxiety_upset_delivered,"[unforeseen, anxiety, upset, delivered, causin...","[unforeseen, anxiety, upset, delivered, causin...","[reassurances, stress, during, distress, anxie...",[These planning applications are causing stres...
202,201,10,201_public_informed_strike_unmade,"[public, informed, strike, unmade, insensitive...","[public, informed, strike, unmade, insensitive...","[evidence, public, responses, concerns, antici...","[Despite numerous requests, the Council on its..."

In [32]:
topic_df[['doc_1', 'doc_2', 'doc_3']] = pd.DataFrame(topic_df['Representative_Docs'].tolist(), index=topic_df.index)

In [33]:
topic_df

,Topic,Count,Name,Representation,MaximalMarginalRelevance,KeyBERTInspired,Representative_Docs,doc_1,doc_2,doc_3
0,-1,1500,-1_to_for_the_this,"[to, for, the, this, and, of, in, be, planning...","[to, for, the, this, and, of, in, be, planning...","[design, trees, parking, space, tree, green, l...",[I strongly oppose to this building applicatio...,I strongly oppose to this building application...,The proposed 3- and 4-storey building will cre...,"For over 20 years, the previous owner of the s..."
1,0,89,0_family_bedroom_flats_roofs,"[family, bedroom, flats, roofs, home, flat, un...","[family, bedroom, flats, roofs, home, flat, un...","[bedroom, family, mix, bed, bedspace, breeding...","[Family houses are needed., Green roofs are pr...",Family houses are needed.,Green roofs are proposed at first floor level ...,Issue with Roof & Green TerracesGreen roofs ar...
2,1,80,1_trees_report_groups_lime,"[trees, report, groups, lime, mature, group, p...","[trees, report, groups, lime, mature, group, p...","[trees, tree, apple, species, gardens, habitat...",[? G7 group of trees all lie within the proper...,? G7 group of trees all lie within the propert...,"2.2 There are, in particular, four groups of t...",3.2 As the trees growing between the boundary ...
3,2,77,2_comments_hearing_comment_judicial,"[comments, hearing, comment, judicial, review,...","[comments, hearing, comment, judicial, review,...","[comments, comment, objection, appeal, refusal...","[We have the following comments:, We have deep...",We have the following comments:,We have deep concerns and find it most strange...,We have deep concerns and find it most strange...
4,3,71,3_objections_my_petition_read,"[objections, my, petition, read, follows, plan...","[objections, my, petition, read, follows, plan...","[objections, petition, objected, rejected, sub...","[My main objections are as follows, The object...",My main objections are as follows,The objections are as follows:,My objections are the following:
...,...,...,...,...,...,...,...,...,...,...
198,197,11,197_driveway_buffer_noise_inaccurate,"[driveway, buffer, noise, inaccurate, traffic,...","[driveway, buffer, noise, inaccurate, traffic,...","[trees, greenery, traffic, congestion, light, ...",[1. Inaccurate and misleading submission docum...,1. Inaccurate and misleading submission docume...,1. Inaccurate and misleading submission docume...,"In respect of the proposed driveway, I would n..."
199,198,11,198_sincerely_yours__,"[sincerely, yours, , , , , , , , ]","[sincerely, yours, , , , , , , , ]","[yours, sincerely, , , , , , , , ]","[Yours sincerely,, Yours sincerely,, Yours sin...","Yours sincerely,","Yours sincerely,","Yours sincerely,"
200,199,11,199_bin_stores_curtilage_212719ful,"[bin, stores, curtilage, 212719ful, extend, cy...","[bin, stores, curtilage, 212719ful, extend, cy...","[amenity, waste, bin, recycling, refuse, bins,...",[Subsection 1(n) states that development is no...,Subsection 1(n) states that development is not...,Subsection 1(n) states that development is not...,Subsection 1(n) states that development is not...
201,200,10,200_unforeseen_anxiety_upset_delivered,"[unforeseen, anxiety, upset, delivered, causin...","[unforeseen, anxiety, upset, delivered, causin...","[reassurances, stress, during, distress, anxie...",[These planning applications are causing stres...,These planning applications are causing stress...,The resubmission of planning applications are ...,The resubmission of planning applications are ...
202,201,10,201_public_informed_strike_unmade,"[public, informed, strike, unmade, insensitive...","[public, informed, strike, unmade, insensitive...","[evidence, public, responses, concerns, antici...","[Despite numerous requests, the Council on its...","Despite numerous requests, the Council on its ...","Finally, does the council know who owns the un...",There has not been enough time for the public ...

In [34]:
topic_df.to_csv('../outputs/topics.csv', index=False)

In [13]:
for i in range(len(topic_df)):
    topic = topic_df.iloc[i]
    print(f"Topic {topic['Topic']}: {topic['Name']} (Size: {topic['Count']})")

Topic -1: -1_to_for_the_this (Size: 1500)
Topic 0: 0_family_bedroom_flats_roofs (Size: 89)
Topic 1: 1_trees_report_groups_lime (Size: 80)
Topic 2: 2_comments_hearing_comment_judicial (Size: 77)
Topic 3: 3_objections_my_petition_read (Size: 71)
Topic 4: 4_bins_refuse_bin_waste (Size: 68)
Topic 5: 5_parking_spaces_cars_street (Size: 66)
Topic 6: 6_safety_security_fire_drug (Size: 62)
Topic 7: 7_tennis_courts_leisure_play (Size: 61)
Topic 8: 8_conservation_area_village_whatever (Size: 60)
Topic 9: 9_amenity_sqm_space_3b5p (Size: 59)
Topic 10: 10_2017_starts_ensure_ask (Size: 59)
Topic 11: 11_distance_metres_between_too (Size: 58)
Topic 12: 12_commercial_evidence_cost_facilities (Size: 58)
Topic 13: 13_amendment_maisonettes_reinstated_amended (Size: 57)
Topic 14: 14_design_look_between_metres (Size: 56)
Topic 15: 15_consultation_june_was_mentioned (Size: 53)
Topic 16: 16_garden_65_golden_rear (Size: 53)
Topic 17: 17_height_massing_floor_golden (Size: 52)
Topic 18: 18_biodiversity_bap_duty_bats (Size: 52)
Topic 19: 19_social_housing_maintenance_affordable (Size: 51)
Topic 20: 20_light_imposing_21_closeby (Size: 51)
Topic 21: 21_park_parking_cars_bays (Size: 47)
Topic 22: 22_trees_conservation_protected_within (Size: 47)
Topic 23: 23_13th_greening_urban_2022 (Size: 46)
Topic 24: 24_garden_character_trees_design (Size: 46)
Topic 25: 25_scale_height_character_design (Size: 46)
Topic 26: 26_park_access_through_gp (Size: 45)
Topic 27: 27_conservation_character_area_keeping (Size: 44)
Topic 28: 28_disabled_parking_bays_court (Size: 43)
Topic 29: 29_affordable_housing_viability_shared (Size: 42)
Topic 30: 30_noise_construction_hours_horrendous (Size: 42)
Topic 31: 31_access_service_road_fire (Size: 42)
Topic 32: 32_density_dense_congested_already (Size: 42)
Topic 33: 33_permission_landlord_granted_planning (Size: 41)
Topic 34: 34_application_planning_revised_skills (Size: 41)
Topic 35: 35_privacy_overlooking_immediately_bordering (Size: 40)
Topic 36: 36_parking_spaces_already_there (Size: 40)
Topic 37: 37_housing_rent_covide_standards (Size: 39)
Topic 38: 38_conservation_trees_character_part (Size: 38)
Topic 39: 39_garden_sunlight_light_receive (Size: 37)
Topic 40: 40_privacy_my_loss_able (Size: 37)
Topic 41: 41_character_out_area_occupy (Size: 37)
Topic 42: 42_sustainable_objective_carbon_active (Size: 36)
Topic 43: 43_open_space_tennis_physical (Size: 36)
Topic 44: 44_disruption_noise_exits_fire (Size: 36)
Topic 45: 45_detached_semi_overdevelopment_density (Size: 36)
Topic 46: 46_impact_neighboring_deleterious_premises (Size: 35)
Topic 47: 47_green_space_contravening_subsection (Size: 35)
Topic 48: 48_congested_parking_already_overcrowding (Size: 34)
Topic 49: 49_environment_ecological_benefactor_solve (Size: 34)
Topic 50: 50_pollution_traffic_noise_air (Size: 34)
Topic 51: 51_amenity_space_open_tennis (Size: 34)
Topic 52: 52_disturbance_noise_medium_construction (Size: 34)
Topic 53: 53_object_strongly_proposal_reasons (Size: 33)
Topic 54: 54_traffic_nursery_servicing_per (Size: 32)
Topic 55: 55_heritage_asset_nile_lodge (Size: 32)
Topic 56: 56_school_snowflake_children_gps (Size: 32)
Topic 57: 57_environmental_effects_negative_life (Size: 32)
Topic 58: 58_heritage_asset_assets_significance (Size: 31)
Topic 59: 59_parking_tylney_rd_presents (Size: 30)
Topic 60: 60_continued_dear_memorandum_chin (Size: 30)
Topic 61: 61_family_bedroom_garden_view (Size: 29)
Topic 62: 62_spaciousness_feature_barratt_dimensions (Size: 29)
Topic 63: 63_objection_oppose_strongly_am (Size: 28)
Topic 64: 64_flooding_flood_risk_subsidence (Size: 28)
Topic 65: 65_daylight_sunlight_bre_27 (Size: 28)
Topic 66: 66_scale_heritage_assets_conservation (Size: 28)
Topic 67: 67_drainage_water_uses_costly (Size: 28)
Topic 68: 68_object_following_strongly_grounds (Size: 27)
Topic 69: 69_overdevelopment_decrease_overcrowding_researching (Size: 27)
Topic 70: 70_rejected_applications_chief_previous (Size: 27)
Topic 71: 71_school_children_primary_dust (Size: 27)
Topic 72: 72_view_operator_remark_defer (Size: 26)
Topic 73: 73_parking_street_off_family (Size: 26)
Topic 74: 74_approved_burden_masterplan_begin (Size: 25)
Topic 75: 75_traffic_noise_nursery_corrected (Size: 25)
Topic 76: 76_typology_symmetrical_uniformity_cottage (Size: 25)
Topic 77: 77_park_underground_car_specified (Size: 25)
Topic 78: 78_tall_sites_buildings_d9 (Size: 25)
Topic 79: 79_parking_si13_impermeable_removals (Size: 25)
Topic 80: 80_privacy_light_daylight_health (Size: 25)
Topic 81: 81_views_conservation_negative_locality (Size: 24)
Topic 82: 82_view_tower_close_grade (Size: 24)
Topic 83: 83_refused_application_refuse_3124 (Size: 24)
Topic 84: 84_nature_similar_interconnected_controversial (Size: 24)
Topic 85: 85_neighbouring_amenity_properties_balconies (Size: 24)
Topic 86: 86_neighbours_detrimental_ugf_belt (Size: 24)
Topic 87: 87_trees_amenity_sticky_significant (Size: 24)
Topic 88: 88_visual_amenity_scale_surrounding (Size: 24)
Topic 89: 89_shop_commercial_purchase_compulsory (Size: 24)
Topic 90: 90_family_street_detached_character (Size: 23)
Topic 91: 91_privacy_overlook_height_overbearing (Size: 23)
Topic 92: 92_park_residual_playground_school (Size: 23)
Topic 93: 93_demolition_foundations_digging_decision (Size: 23)
Topic 94: 94_ahmed_stephen_mottershead_mr (Size: 23)
Topic 95: 95_tree_canopy_cover_considering (Size: 23)
Topic 96: 96_density_relief_green_grain (Size: 22)
Topic 97: 97_noise_traffic_impact_adverse (Size: 22)
Topic 98: 98_carbon_neutrality_offset_credentials (Size: 22)
Topic 99: 99_parking_adequacy_synopsis_struggles (Size: 22)
Topic 100: 100_daylight_adf_bs_median (Size: 22)
Topic 101: 101_safety_dangerous_parking_vehicles (Size: 22)
Topic 102: 102_health_mental_nhs_costs (Size: 22)
Topic 103: 103_height_shadow_sunlight_light (Size: 21)
Topic 104: 104_elderly_vulnerable_respectfully_unhelpful (Size: 21)
Topic 105: 105_wildlife_bats_habitat_birds (Size: 21)
Topic 106: 106_privacy_overlook_overlooking_loss (Size: 21)
Topic 107: 107_relocated_affordable_temporary_themselves (Size: 21)
Topic 108: 108_listed_1990_appearance_72 (Size: 20)
Topic 109: 109_conclusion_summary_summarise_observations (Size: 20)
Topic 110: 110_doors_rebound_shining_light (Size: 20)
Topic 111: 111_privacy_light_windows_overlooking (Size: 20)
Topic 112: 112_trees_destruction_hedges_virtual (Size: 20)
Topic 113: 113_membership_household_car_each (Size: 20)
Topic 114: 114_dear_mr_ms_hi (Size: 20)
Topic 115: 115_retaining_wall_boundary_red (Size: 20)
Topic 116: 116_traffic_generation_increased_logged (Size: 20)
Topic 117: 117_light_overshadowing_21st_calculations (Size: 19)
Topic 118: 118_listed_you_hope_flood (Size: 19)
Topic 119: 119_disabled_disability_equality_sector (Size: 19)
Topic 120: 120_safety_pedestrians_traffic_junction (Size: 19)
Topic 121: 121_congested_congestion_peak_transport (Size: 19)
Topic 122: 122_transport_highways_links_6b (Size: 19)
Topic 123: 123_nature_overbearing_storey_units (Size: 19)
Topic 124: 124_pollution_noise_construction_air (Size: 18)
Topic 125: 125_ugly_history_distinctiveness_registry (Size: 18)
Topic 126: 126_impact_parking_class_use (Size: 18)
Topic 127: 127_air_pollution_quality_extraction (Size: 18)
Topic 128: 128_climate_change_flood_risk (Size: 18)
Topic 129: 129_drainage_flood_risk_flooding (Size: 18)
Topic 130: 130_overlook_overlooking_hand_windows (Size: 18)
Topic 131: 131_thank_you_thanks_thankyou (Size: 18)
Topic 132: 132_quality_design_dm01_policies (Size: 18)
Topic 133: 133_compiled_found_rental_pdf (Size: 18)
Topic 134: 134_retaining_wall_brent_demolished (Size: 18)
Topic 135: 135_email_received_objection_gmcintosh1 (Size: 17)
Topic 136: 136_homeless_taken_provision_away (Size: 17)
Topic 137: 137_scale_extant_ambition_heat (Size: 17)
Topic 138: 138_bins_parking_look_realignment (Size: 17)
Topic 139: 139_context_contribution_outlines_underutilised (Size: 16)
Topic 140: 140_multi_reintroduction_nine_reasonable (Size: 16)
Topic 141: 141_affordable_neighbourhoods_affordability_afford (Size: 16)
Topic 142: 142_car_push_mayor_parking (Size: 15)
Topic 143: 143_amenity_design_character_local (Size: 15)
Topic 144: 144_design_issues_keeping_with (Size: 15)
Topic 145: 145_services_appropriate_traffic_jobs (Size: 15)
Topic 146: 146_t11_t9_41_t10 (Size: 15)
Topic 147: 147_image_ecia_topographical_picture (Size: 15)
Topic 148: 148_quality_accommodation_c2_stipulates (Size: 15)
Topic 149: 149_eight_surrounded_suit_six (Size: 15)
Topic 150: 150_height_simulation_frames_brown (Size: 15)
Topic 151: 151_dust_my_noise_construction (Size: 15)
Topic 152: 152_visual_adverse_impact_89 (Size: 15)
Topic 153: 153_bedrooms_badge_blue_27 (Size: 14)
Topic 154: 154_biodiversity_concreting_protection_green (Size: 14)
Topic 155: 155_distance_privacy_rooms_overlooking (Size: 14)
Topic 156: 156_kind_regards_wishes_best (Size: 14)
Topic 157: 157_sir_dear_madam_sirs (Size: 14)
Topic 158: 158_sunlight_receive_heat_department (Size: 14)
Topic 159: 159_pedestrian_accident_width_path (Size: 14)
Topic 160: 160_1970_example_impacted_heritage (Size: 14)
Topic 161: 161_car_parking_t6_access (Size: 13)
Topic 162: 162_supply_electricity_grid_water (Size: 13)
Topic 163: 163_wildlife_sensitive_pea_natural (Size: 13)
Topic 164: 164_mandate_positions_replanting_greenery (Size: 13)
Topic 165: 165_impact_das_forwarded_concentration (Size: 13)
Topic 166: 166_toads_wildlife_breed_ponds (Size: 13)
Topic 167: 167_view_dramatically_obstruct_vacant (Size: 13)
Topic 168: 168_archaeological_devastating_disagree_negative (Size: 13)
Topic 169: 169_biodiversity_renewable_environment_habitats (Size: 13)
Topic 170: 170_homeowning_remotely_income_afford (Size: 13)
Topic 171: 171_habitable_negligible_228_5rh (Size: 13)
Topic 172: 172_ptal_transport_ptal3_accepts (Size: 13)
Topic 173: 173_housing_affordable_wisely_193 (Size: 13)
Topic 174: 174_heritage_explicitly_heading_specifically (Size: 13)
Topic 175: 175_character_out_impacting_skyline (Size: 12)
Topic 176: 176_pollution_climate_air_combat (Size: 12)
Topic 177: 177_subsection_schedule_class_implement (Size: 12)
Topic 178: 178_construction_damage_proximity_mature (Size: 12)
Topic 179: 179_transport_bhra_safer_recommendations (Size: 12)
Topic 180: 180_happen_let_stop_don (Size: 12)
Topic 181: 181_shortage_removes_longer_homeless (Size: 12)
Topic 182: 182_value_age_yield_property (Size: 12)
Topic 183: 183_neighbour_signatures_newsletters_got (Size: 12)
Topic 184: 184_open_mental_precisely_darker (Size: 12)
Topic 185: 185_historic_areas_townscape_conservation (Size: 12)
Topic 186: 186_private_9th_leases_ordinary (Size: 12)
Topic 187: 187_obj_email_received_by (Size: 11)
Topic 188: 188_meeting_need_housing_local (Size: 11)
Topic 189: 189_crowded_engine_family_rental (Size: 11)
Topic 190: 190_montpelier_conservation_queen_setting (Size: 11)
Topic 191: 191_clarifies_widening_centre_west (Size: 11)
Topic 192: 192_private_use_wider_community (Size: 11)
Topic 193: 193_management_policies_2012_2013 (Size: 11)
Topic 194: 194_faithfully_yours_your_ (Size: 11)
Topic 195: 195_available_outdated_methods_master (Size: 11)
Topic 196: 196_reference_22_s73_234919ful (Size: 11)
Topic 197: 197_driveway_buffer_noise_inaccurate (Size: 11)
Topic 198: 198_sincerely_yours__ (Size: 11)
Topic 199: 199_bin_stores_curtilage_212719ful (Size: 11)
Topic 200: 200_unforeseen_anxiety_upset_delivered (Size: 10)
Topic 201: 201_public_informed_strike_unmade (Size: 10)

In [21]:
# function which string the represnetation words toegther into a single string
def get_topic_words(topic_model, topic_id):
    topic_words = topic_model.get_topic(topic_id)
    return ", ".join([word for word, _ in topic_words])

In [22]:
get_topic_words(topic_model, 0)

'family, bedroom, flats, roofs, home, flat, units, person, needed, two'

In [23]:
topic_model.get_representative_docs(topic=0)

['Family houses are needed.',
 'Green roofs are proposed at first floor level above kitchen/dining rooms for proposed units 2 and 3. There is a risk that the new residents could gain access to these so it will be important that conditions are set out to ensure that the windows facing onto the green roofs are non-openable.The four-bedroom proposed houses have flat roofs facing north so that there is easy access to intruders to climb into the Grendon Gardens properties, unseen from the Newland Court road. There seems to be no provision for security lighting to prevent this happening. There need to be conditions placed so that these roofs cannot be used as terraces by the residents of the new properties.',
 'Issue with Roof & Green TerracesGreen roofs are proposed at first floor level above kitchen/dining rooms for Unit Types 03 and 04. There is a risk that the new residents could gain access to these so it will be important that conditions are set out to ensure that the windows facing onto the green roofs are non-openable.The four-bedroom proposed houses have flat roofs facing north so that there is easy access to intruders to climb into the Grendon Gardens properties, unseen from the Newland Court road. This also applies to the two-bedroom houses. There seems to be no provision for security lighting to prevent this happening. There need to be conditions placed so that these roofs cannot be used as terraces by the residents of the new properties.']

In [ ]:
# tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-base")
# model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-base")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LlamaTokenizer'.
The class this function is called from is 'T5Tokenizer'.

TypeError: not a string

In [ ]:
from transformers import T5ForConditionalGeneration, T5Tokenizer

model = T5ForConditionalGeneration.from_pretrained("dafilab/chat-title-generator")
tokenizer = T5Tokenizer.from_pretrained("dafilab/chat-title-generator", legacy=False)



# text = """How can I access the GPU of my other computer remotely for ML training?
# To access your other computer's GPU remotely for machine learning (ML) training,
# you need to set up remote access to the machine and ensure that it can properly leverage the GPU for computations.
# There are several ways to do this, depending on your operating system and the tools you prefer to use."""
# print(generate_chat_title(text))

In [52]:
keywords = get_topic_words(topic_model, 1)
rep_docs = topic_model.get_representative_docs(topic=1)
# input_text = f"""I have a topic that contains the following documents:{rep_docs}
# I have a  topic is described by the following keywords: {keywords}

# Based on the information above, extract a short but highly descriptive topic label of at most 5 words."""

input_text = f"""Generate a short but highly descriptive label of at most 8 words for planning objections characterised by these keywords: {keywords}"""

In [63]:
def generate_chat_title(keys):
    input_text = "short title: {keys}"
    inputs = tokenizer(input_text, return_tensors="pt", truncation=True, max_length=512)
    outputs = model.generate(
        input_ids=inputs.input_ids,
        max_length=64,
        num_beams=4,
        early_stopping=True,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print(generate_chat_title(keys=keywords))

Keys #39;

In [64]:
rep_docs

["? G7 group of trees all lie within the property of 2 Corringham Road. In the earlier Waterman Report of September 2022, in the Schedule of Existing Trees (p 34), G7 is described as 'Off-site', wording now omitted in their new report.",
 '2.2 There are, in particular, four groups of trees in the back gardens of houses in Grendon Gardens, close to the boundary with the proposed development, which would be affected by the application. Groups G4, G6 and G17 all comprise mainly Common Lime trees, while group G13 is a hedge of Leyland Cypress. I have highlighted these groups on image 2.',
 '3.2 As the trees growing between the boundary fences of the back gardens of homes in , and the side boundary of 2 Corringham , and the roadway are within the BHCA, they have the same rights of protection as those in the "line of trees" including Groups G4, G6, G13 and G17 considered in my earlier comments.']

In [53]:
print(input_text)
input_ids = tokenizer(input_text, return_tensors="pt").input_ids

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))

Generate a short but highly descriptive label of at most 8 words for planning objections characterised by these keywords: trees, report, groups, lime, mature, group, pruning, line, corringham, g4
<pad> corringham</s>

In [ ]:


input_text = """I have a topic that contains the following documents:[DOCUMENTS]
The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short but highly descriptive topic label of at most 5 words. Make sure it is in the following format:
topic: <topic label>"""

input_ids = tokenizer(input_text, return_tensors="pt").input_ids

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))

In [17]:
representation_model = KeyBERTInspired()

# define the topic model with parameters 
topic_model = BERTopic(embedding_model=sentence_model,
                       hdbscan_model=hdbscan_model, 
                       umap_model=umap_model, 
                       representation_model=representation_model,
                       verbose=True, 
                       calculate_probabilities=True)

# fit the model to the cleaned text
topics, probs = topic_model.fit_transform(cleaned_text, embeddings)

# Display the topics found
topic_model.get_topic_info()

2025-06-11 08:44:05,111 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-11 08:44:16,160 - BERTopic - Dimensionality - Completed ✓
2025-06-11 08:44:16,162 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-11 08:44:24,501 - BERTopic - Cluster - Completed ✓
2025-06-11 08:44:24,507 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-06-11 08:44:44,344 - BERTopic - Representation - Completed ✓

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1498,-1_trees_tree_space_design,"[trees, tree, space, design, green, am, parkin...",[Allowing this development would set a very un...
1,0,88,0_bedroom_family_mix_bed,"[bedroom, family, mix, bed, bedspace, breeding...","[Family houses are needed., Green roofs are pr..."
2,1,82,1_trees_tree_leaf_apple,"[trees, tree, leaf, apple, species, gardens, r...",[- G7 group of trees all lie within the proper...
3,2,77,2_comments_comment_objection_appeal,"[comments, comment, objection, appeal, refusal...","[We have the following comments:, We have deep..."
4,3,71,3_objections_petition_objected_rejected,"[objections, petition, objected, rejected, sub...","[My main objections are as follows, My objecti..."
...,...,...,...,...,...
198,197,11,197_yours_your_faithfully_,"[yours, your, faithfully, , , , , , , ]","[Yours Faithfully,, Yours faithfully,, Yours f..."
199,198,11,198_email_received_obj_documents,"[email, received, obj, documents, receipt, con...","[Obj received by email, Obj received by email,..."
200,199,11,199_management_application_policies_considerat...,"[management, application, policies, considerat...",[I support this application as it meets all po...
201,200,11,200_amenity_waste_bin_recycling,"[amenity, waste, bin, recycling, refuse, bins,...",[Subsection 1(n) states that development is no...
202,201,10,201_amenity_impact_outlook_of,"[amenity, impact, outlook, of, residential, on...",[2) Impact on the amenity of the existing buil...

In [20]:
representation_model = PartOfSpeech("Bea-Taylor/objection_fine_tuned_4")

# define the topic model with parameters 
topic_model = BERTopic(embedding_model=sentence_model,
                       hdbscan_model=hdbscan_model, 
                       umap_model=umap_model, 
                       representation_model=representation_model,
                       verbose=True, 
                       calculate_probabilities=True)

# fit the model to the cleaned text
topics, probs = topic_model.fit_transform(cleaned_text, embeddings)

# Display the topics found
topic_model.get_topic_info()

OSError: [E050] Can't find model 'Bea-Taylor/objection_fine_tuned_4'. It doesn't seem to be a Python package or a valid path to a data directory.

In [ ]:
# identify the topics with a probability greater than 0.02
# index where probs[0]>0.02
high_prob_indices = np.where(probs[0] > 0.02)[0]
# Get the topics for these indices
high_prob_topics = [get_topic_words(topic_model, i) for i in high_prob_indices]
# Get the probabilities for these indices
high_prob_probs = [probs[0][i] for i in high_prob_indices]
for topic, prob in zip(high_prob_topics, high_prob_probs):
    print(f"Topic: [{topic}], Probability: {prob:.4f}")

Topic: [park, underground, car, specified, quantum, 2017, 108, access, subsequent, completed], Probability: 0.1482

In [ ]:
# add the topics and probabilities to the train_df_split dataframe

all_topic_list =[]
all_prob_list = []
for i in range(len(train_df_split)):
    high_prob_indices = np.where(probs[i] > 0.02)[0]
    high_prob_topics = [get_topic_words(topic_model, i) for i in high_prob_indices]
    high_prob_probs = [probs[i][j] for j in high_prob_indices]
    topic_list = []
    prob_list = []
    for topic, prob in zip(high_prob_topics, high_prob_probs):
        topic_list.append(topic)
        prob_list.append(prob)
    all_topic_list.append(topic_list)
    all_prob_list.append(prob_list)

train_df_split['topics'] = all_topic_list
train_df_split['probs'] = all_prob_list

In [ ]:
train_df_split

,id,council,comment_id,application_id,address,stance,date,comment_text,add_date,lat,lon,cleaned_comment_text,original_comment_id,topics,probs
0,108039,Ealing,214950FUL_129,214950FUL,57A Woodhurst Road Acton London W3 6SR W3 6SR,Objects,2021-09-15,I am not sure why Ealing Council are hell bent...,2025-05-01,51.510510,-0.268640,I am not sure why Council are hell bent of bui...,0,"[park, underground, car, specified, quantum, 2...",[0.1482378501837773]
1,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,It is obvious from all the detailed reading of...,1,"[comments, hearing, comment, judicial, renewal...",[0.03403126291932642]
2,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,The proposed development would be entirely out...,1,"[park, residual, playground, school, 14, our, ...",[1.0]
3,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,The area on which the property is proposed to ...,1,"[biodiversity, bap, duty, bats, wildlife, habi...",[0.6223742666706982]
4,75255,Ealing,216308FUL_21,216308FUL,2 Alwyne Road LONDON W7 3EN W7 3EN,Objects,2022-01-08,It is obvious from all the detailed reading of...,2025-04-07,NaN,NaN,It is also inappropriate that residents contin...,1,"[heritage, asset, lodges, nile, preserved, sta...",[0.020380490857612326]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6845,81834,Ealing,205161FUL_107,205161FUL,19 Lillian Avenue London W3 9AN,Objects,2021-02-06,The proposal is far from fit for purpose. Curr...,2025-04-09,51.502026,-0.284986,"- If parked on the road, where a high rate of ...",998,"[bins, refuse, waste, bin, rubbish, recycling,...",[0.6857589171189096]
6846,81834,Ealing,205161FUL_107,205161FUL,19 Lillian Avenue London W3 9AN,Objects,2021-02-06,The proposal is far from fit for purpose. Curr...,2025-04-09,51.502026,-0.284986,https://www..gov.uk/downloads/201167/rubbish_a...,998,"[bins, refuse, waste, bin, rubbish, recycling,...",[1.0]
6847,81834,Ealing,205161FUL_107,205161FUL,19 Lillian Avenue London W3 9AN,Objects,2021-02-06,The proposal is far from fit for purpose. Curr...,2025-04-09,51.502026,-0.284986,"Finally, from a personal standpoint, I would l...",998,"[parking, spaces, already, there, allocated, 1...","[0.025656633649377543, 0.1656856770903388, 0.0..."
6848,76454,Barnet,24/1146/OUT_13,24/1146/OUT,91 Margaret Road New Barnet EN4 9RA,Objects,2024-04-20,The details of this audacious planning applica...,2025-04-08,51.650399,-0.164110,The details of this audacious planning applica...,999,"[unforeseen, anxiety, upset, covid19, delivere...",[0.07481701160027006]
6849,76454,Barnet,24/1146/OUT_13,24/1146/OUT,91 Margaret Road New Barnet EN4 9RA,Objects,2024-04-20,The details of this audacious planning applica...,2025-04-08,51.650399,-0.164110,The applicant is not interested in getting the...,999,"[objections, my, petition, follows, read, plan...",[0.5813214727119856]

In [ ]:
# merge the sentences back to the original comments
new_df = nlp_tasks.merge_sentences_back_to_comments(train_df_split, text_column='cleaned_comment_text',
                                           topic_column='topics')

In [ ]:
new_df['topics'][1]

['amendment, maisonettes, reinstated, amended, submission, forward, elsewhere, proposals, mews, brought',
 'biodiversity, bap, duty, bats, wildlife, habitat, species, tit, 2027, ealings',
 'comments, hearing, comment, judicial, renewal, review, appeal, reading, have, find',
 'heritage, asset, lodges, nile, preserved, status, archaeological, grounds, possible, assessment',
 'park, residual, playground, school, 14, our, llanvanor, bin, space, urban',
 'refused, application, refuse, 223124, should, opportunity, barrister, objection, writing, dismiss']